
class AppStrings {
  static const Map<String, Map<String, String>> languages = {
    'ru': {
      'title': 'Обмен навыками',
      'search_hint': 'Поиск по городу...',
      'empty_text': 'Ничего не найдено',
      'add_btn': 'Предложить',
      'new_skill_title': 'Новый навык',
      'label_name': 'Ваше имя',
      'label_skill': 'Название навыка',
      'label_desc': 'Описание',
      'label_loc': 'Город / Локация',
      'btn_publish': 'Опубликовать',
      'btn_contact': 'Связаться',
      'sent_msg': 'Сообщение отправлено!',
      'author': 'Автор',
      'where': 'Где',
      'desc_header': 'Описание',
      'fill_error': 'Заполните поле',
    },
    'en': {
      'title': 'Skill Swap',
      'search_hint': 'Search by city...',
      'empty_text': 'Nothing found',
      'add_btn': 'Offer',
      'new_skill_title': 'New Skill',
      'label_name': 'Your Name',
      'label_skill': 'Skill Title',
      'label_desc': 'Description',
      'label_loc': 'City / Location',
      'btn_publish': 'Publish',
      'btn_contact': 'Contact',
      'sent_msg': 'Message sent!',
      'author': 'Author',
      'where': 'Where',
      'desc_header': 'Description',
      'fill_error': 'Fill this field',
    },
    'tr': {
      'title': 'Yetenek Takası',
      'search_hint': 'Şehir ara...',
      'empty_text': 'Bulunamadı',
      'add_btn': 'Teklif Et',
      'new_skill_title': 'Yeni Yetenek',
      'label_name': 'Adınız',
      'label_skill': 'Yetenek Adı',
      'label_desc': 'Açıklama',
      'label_loc': 'Şehir / Konum',
      'btn_publish': 'Yayınla',
      'btn_contact': 'İletişime Geç',
      'sent_msg': 'Mesaj gönderildi!',
      'author': 'Yazar',
      'where': 'Nerede',
      'desc_header': 'Açıklama',
      'fill_error': 'Bu alanı doldurun',
    },
    'az': {
      'title': 'Bacarıq Mübadiləsi',
      'search_hint': 'Şəhər axtar...',
      'empty_text': 'Tapılmadı',
      'add_btn': 'Təklif Et',
      'new_skill_title': 'Yeni Bacarıq',
      'label_name': 'Adınız',
      'label_skill': 'Bacarıq Adı',
      'label_desc': 'Təsvir',
      'label_loc': 'Şəhər / Məkan',
      'btn_publish': 'Dərc et',
      'btn_contact': 'Əlaqə saxla',
      'sent_msg': 'Mesaj göndərildi!',
      'author': 'Müəllif',
      'where': 'Harada',
      'desc_header': 'Təsvir',
      'fill_error': 'Bu xananı doldurun',
    },
  };
}